services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app_net

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
    ports:
      - "5432:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    networks:
      - app_net

networks:
  app_net:
    driver: bridge